### ISSUE TITLE
Should allow +c +o interfaces

### ISSUE THREAD

**Issue by j4cbo** [dropbox/djinni#81]
We currently allow interfaces that are *both* +c and +j (see TokenTest). Need to do the same for ObjC.

Right now we generate classes for `+c` and protocols for `+o`. An interface that's `+c +o` would be a protocol with an old-style CppProxy implementation.

**Comment by mknejp** [comment]
So should `+c +o` create `@protocol` or `@interface`? I didn't find a conslusive answer to this myself. I tend towards `@interface` since `@protocol` is just a bit weird in general, especially since class (static) methods don't have implementations, which was one of the reasons users previously had to include the CppProxy headers (very awkward).

**Comment by j4cbo** [comment]
I was thinking `@protocol`, and will probably just disallow static methods on `+c +o`.

**Comment by mknejp** [comment]
That creates a strange asymmetry if they are allowed for `+j`

**Comment by j4cbo** [comment]
Yep, they shouldn't be allowed on `+c +o` or `+c +j +o` either (I think they currently are, but will probably generate broken code).

**Comment by j4cbo** [comment]
`+c +j` rather.

**Comment by mknejp** [comment]
Well, I guess it is doable. The CppProxy has to implement the static method like usual and clients have to invoke it from Objective-C using
```objc
id<Thing> thing = [ThingFactory createThing]; // returns ThingCppProxy
[[thing class] doThing];
```
You cannot, however, make the factory method a member of the `+c +o` interface itself as you require a runtime object to get the class from in the first place. So it's fine except for this one (very frequent and necessary) use case.

**Comment by mknejp** [comment]
Gave this some more thought and I think you're right. The point of a static method is it exists only once. However any combination of more than one `+x` is ambiguous about which language implements the static method, so it probably shouldn't be allowed at all.

**Comment by j4cbo** [comment]
I've pushed f0aec36d99764ca62903ba58fbb9c4af9c886c5 to a branch to let it bake for a bit before merging into master. The Carousel team is working on some refactoring to use this - if they don't run into any showstoppers then I'll merge it in and call it done.

**Comment by mknejp** [comment]
You know this makes me think whether `+c` is even necessary at all. On the C++ side whether `+c` is present or not makes no difference, there's always just a plain C++ abstract base class clients can do whatever with.

It only makes a difference for the glue code and I was wondering: would it make big of a difference to always imply `+c`? *Because* the generated C++ code doesn't distinguish whether `+j`/`+o` is there or not why even bother putting the `+c` mark in there.

In the glue code if the `dynamic_cast<Proxy*>` fails one received some other `T` derived from the interface. Theoretically one could wrap that inside a new proxy and let the Java/Obj-C code interface with it instead.

**Comment by j4cbo** [comment]
I think it's useful to limit the size of the generated code (on both the Java and JNI side), since code size and Java method count can be concerns.

**Comment by mknejp** [comment]
Whether `+c` exists or not does not impact the generated Java code. And in any real world app the size of the Djinni glue code should be insignificant compared to the rest of the application.

I'm still not certain if it is possible to drop the `+c` and make it work in all cases, that requires some more experimentation.

**Comment by mknejp** [comment]
OK, correction. There is a difference in Java generation. I just wonder whether it's really necessary...

**Comment by j4cbo** [comment]
Done as of f0aec36d99764ca62903ba58fbb9c4af9c886c54
